# Generated by Django 5.1.1 on 2024-09-13 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3)])),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Enter Valid Email')])),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3)])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3)])),
                ('middle_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(1)])),
            ],
        ),
    ]
