# Generated by Django 5.1.1 on 2024-09-15 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installed_capacity_monitored', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('sites_active_on_platform', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('mwh_monitored', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('tons_of_co2_offset', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.BinaryField()),
                ('title', models.TextField(max_length=50, validators=[django.core.validators.MinLengthValidator(8)])),
                ('sub_title', models.TextField(validators=[django.core.validators.MinLengthValidator(15)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_duration', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_time', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_icon', models.BinaryField()),
                ('company_name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)])),
                ('testimonial', models.TextField()),
                ('writer_name', models.CharField(max_length=50)),
                ('writer_post', models.CharField(max_length=30)),
            ],
        ),
    ]
