# Generated by Django 5.1.1 on 2024-09-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0002_bannernumber_blogs_demo_subscription_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
